
language: r

warnings_are_errors: true

sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_binary_packages:
 - stringr
 - plyr
 - XML
 
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
  
after_failure: "cat /home/travis/build/systeminsights/mtconnectR/mtconnectR.Rcheck/00check.log"

dist: xenial